const express = require('express');
const router = express.Router();
const { createBooking, getMyBookings, getBooking, cancelBooking, getAllBookings, getBookingStats } = require('../controllers/bookingController');
const { protect, adminOnly } = require('../middleware/auth');
router.post('/', protect, createBooking);
router.get('/my', protect, getMyBookings);
router.get('/stats', protect, adminOnly, getBookingStats);
router.get('/all', protect, adminOnly, getAllBookings);
router.get('/:id', protect, getBooking);
router.put('/:id/cancel', protect, cancelBooking);
module.exports = router;