const express = require('express');
const router = express.Router();
const { getPackages, getFeaturedPackages, getPackage, createPackage, updatePackage, deletePackage } = require('../controllers/packageController');
const { protect, adminOnly } = require('../middleware/auth');
router.get('/', getPackages);
router.get('/featured', getFeaturedPackages);
router.get('/:id', getPackage);
router.post('/', protect, adminOnly, createPackage);
router.put('/:id', protect, adminOnly, updatePackage);
router.delete('/:id', protect, adminOnly, deletePackage);
module.exports = router;